version: "3.7"
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/home/app/
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  scraper:
    build:
      context: .
      dockerfile: ./scraper/Dockerfile
    restart: on-failure
