version: "3.7"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=local-leader
    ports:
      - "5432:5432"
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  scraper:
    build:
      dockerfile: ./scraper.Dockerfile 
    depends_on:
      - db

  web:
    build:
      dockerfile: ./api.Dockerfile
    environment:
      - DB_HOST=db
    ports:
      - "5000:5000"
    depends_on:
      - db
      - scraper
    restart: on-failure

volumes:
  db-data:

