version: "3.7"
services:
  web:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app/:/home/app/
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  scraper:
    build: ./app
    entrypoint: python3 scraper.py
    depends_on:
      - db
    # restart: on-failure
